<?php

/** @var \Codebrainbv\PostcodeCheckout\Block\Config $block */
$configuredProvider = $block->getConfiguredProvider();
$jsFiles = $block->getHyvaAccountJsFiles();
$nonce = $block->getNonce();
?>

<script type="text/javascript" nonce="<?= $nonce ?>">
    window.pcm2_config = <?= json_encode($block->getJsConfig(), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT) ?>;
    window.pcm2_translations = <?= json_encode($block->getTranslations(), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT) ?>;
</script>

<!-- 
    Postcode Checkout Hyva Account loader
-->

<script type="text/javascript" nonce="<?= $nonce ?>">
    addEventListener("DOMContentLoaded", (event) => {
        console.log('Hyvä detected - loading scripts via <script> tags');
        var head = document.head || document.getElementsByTagName('head')[0];
        (async function() {
            const files = <?= json_encode($jsFiles) ?>;
            for (const path of files) {
                const script = document.createElement('script');
                script.src = '<?= $block->getViewFileUrl('') ?>/' + path + '.js';
                
                head.appendChild(script);
            }
        })();
    });
</script>